// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: authors.sql

package db

import (
	"context"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (last_name, first_name, middle_name)
VALUES (?, ?, ?)
RETURNING id
`

type CreateAuthorParams struct {
	LastName   string
	FirstName  string
	MiddleName string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.LastName, arg.FirstName, arg.MiddleName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUniqueAuthor = `-- name: GetUniqueAuthor :one
SELECT id, first_name, last_name, middle_name FROM authors WHERE last_name=? AND first_name=? AND middle_name=?
`

type GetUniqueAuthorParams struct {
	LastName   string
	FirstName  string
	MiddleName string
}

func (q *Queries) GetUniqueAuthor(ctx context.Context, arg GetUniqueAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, getUniqueAuthor, arg.LastName, arg.FirstName, arg.MiddleName)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
	)
	return i, err
}
