// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type Author struct {
	ID         int64
	FirstName  string
	LastName   string
	MiddleName string
}

type AuthorsBook struct {
	BookID   int64
	AuthorID int64
}

type Book struct {
	ID            int64
	Title         string
	PublishedDate sql.NullInt64
	Description   sql.NullString
	Edition       sql.NullString
}

type BooksCollection struct {
	BookID       int64
	CollectionID int64
}

type BooksGenre struct {
	BookID  int64
	GenreID int64
}

type Collection struct {
	ID   int64
	Name string
}

type Genre struct {
	ID   int64
	Name string
}
